# Generated by Django 5.2 on 2025-04-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_label', models.TextField(blank=True, null=True)),
                ('account_id', models.TextField(blank=True, null=True)),
                ('region', models.TextField(blank=True, null=True)),
                ('host_id', models.TextField(blank=True, null=True)),
                ('host_ip_address', models.TextField(blank=True, null=True)),
                ('host_name', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_check', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_monitored', models.BooleanField(default=True)),
                ('downtime_allotment', models.IntegerField(default=0)),
                ('last_allotment_reset', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
