# Generated by Django 5.2 on 2025-05-08 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_hosts_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hosts',
            old_name='id',
            new_name='uuid',
        ),
    ]
