# Generated by Django 5.2.1 on 2025-05-13 18:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_id_hosts_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosts',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
