# Generated by Django 5.2.1 on 2025-05-14 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_hosts_id_alter_hosts_uuid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='GlobalSettings',
        ),
    ]
