# Generated by Django 5.2.1 on 2025-05-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20250514_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosts',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
