# Generated by Django 5.2.1 on 2025-05-14 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_hosts_last_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hosts',
            name='last_active',
        ),
    ]
