# Generated by Django 5.2.1 on 2025-05-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_hosts_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosts',
            name='monitor_params',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hosts',
            name='monitor_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
