# Generated by Django 5.2.1 on 2025-05-14 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0002_monitorstatus_id_alter_monitorstatus_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitorstatus',
            old_name='last_activity',
            new_name='last_update',
        ),
    ]
