# Generated by Django 5.2.1 on 2025-05-14 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0003_rename_last_activity_monitorstatus_last_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitorstatus',
            old_name='last_update',
            new_name='last_active',
        ),
    ]
